apiVersion: v1
kind: Template
labels:
  template: kebechet-cronjob
  thoth: 0.1.0
metadata:
  name: kebechet-cronjob
  annotations:
    description: This is Kebechet CronJob, this template is meant to be used by DevOps...
    openshift.io/display-name: Kebechet CronJob
    version: 0.1.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: kebechet
    labels:
      app: kebechet
  spec:
    schedule: "*/30 * * * *"
    suspend: true
    successfulJobsHistoryLimit: 10
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: kebechet-job
              name: kebechet
              env:
              - name: GITHUB_OAUTH_TOKEN
                valuefrom:
                  secretkeyref:
                    key: token
                    name: kebechet-github
              - name: KEBECHET_CONFIG
                valuefrom:
                  configmapkeyref:
                    key: thoth
                    name: kebechet
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
            restartPolicy: Never
