apiVersion: v1
kind: Template
labels:
  template: kebechet-cronjob
  thoth: 0.1.0
metadata:
  name: kebechet-cronjob
  annotations:
    description: This is Kebechet CronJob, this template is meant to be used by DevOps...
    openshift.io/display-name: Kebechet CronJob
    version: 0.1.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: kebechet
    labels:
      app: thoth
      component: kebechet
  spec:
    schedule: "* * * * *"
    suspend: false
    successfulJobsHistoryLimit: 2
    failedJobsHistoryLimit: 1
    startingDeadlineSeconds: 90
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: kebechet-job
              name: kebechet
              args: ["./kebechet-cli", "--verbose", "--github-token", "${GITHUB_OAUTH_TOKEN}", "run", "/opt/app-root/etc/kebechet.d/thoth.conf"]
              env:
              - name: APP_FILE
                value: "kebechet-cli"
              - name: GITHUB_OAUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: token
                    name: kebechet-github
              volumeMounts:
              - name: config
                mountPath: /opt/app-root/etc/kebechet.d/
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
            restartPolicy: Never
            volumes:
              - name: config
                configMap:
                  name: kebechet
                  items:
                  - key: thoth
                    path: thoth.conf