---
- name: Playbook to validate Thoth's Kebechet Bot deployment
  tags:
    - openshift
    - thoth
    - bot
    - devops

  hosts: localhost
  vars:
    OPENSHIFT_MASTER_URL: "{{ lookup('env','OCP_URL') }}"
    OPENSHIFT_AUTH_TOKEN: "{{ lookup('env','OCP_TOKEN') }}"
    # THOTH_FRONTEND_NAMESPACE should be provided via command like argument
    
  gather_facts: false
  connection: local

  tasks:
  - name: "checking for Secrets"
    command: "oc get secret {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - kebechet-github
    changed_when: False

  - name: "checking for ConfigMap"
    command: "oc get configmap {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - kebechet
    changed_when: False

  - name: "checking for ImageStreams"
    command: "oc get {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - "imagestreams/python-36-centos7"
      - "imagestreams/python-36-centos7-git"
      - "imagestreams/kebechet-job"
    changed_when: False

  - name: "checking for BuildConfigs"
    command: "oc get buildconfig {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - "kebechet-job"
      - "python-36-centos7-git"
    changed_when: False

  - name: "checking for CronJobs"
    command: "oc get cronjob {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - "kebechet"
    changed_when: False